INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (1, 1);
INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (1, 2);
INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (2, 1);
INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (2, 2);
INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (3, 1);
INSERT INTO PUBLIC.USER_ENVIRONNEMENT (USER_ID, ENVIRONNEMENTS_ID) VALUES (3, 2);