INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (1, 'TEST DIVISION 2', 'TEST');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (97, 'NEW', 'NEW');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (129, 'RISK', 'RISK DIVISION');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (161, 'MARKETING', 'MARKETING');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (193, 'IG', 'IG');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (225, 'NOUVELLE', 'NOUVELLE');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (226, 'TEST', 'TEST');
INSERT INTO PUBLIC.DIVISION (ID, NAME_DIVISION, DESCRIPTION) VALUES (257, 'A DIVISION', 'A DIVISION');