INSERT INTO PUBLIC.ENVIRONNEMENT (ID, ENVIRONNEMENT_NAME) VALUES (1, 'DEV');
INSERT INTO PUBLIC.ENVIRONNEMENT (ID, ENVIRONNEMENT_NAME) VALUES (2, 'STAGING');
INSERT INTO PUBLIC.ENVIRONNEMENT (ID, ENVIRONNEMENT_NAME) VALUES (3, 'PROD');