INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 7', 33, 1, 'BB', 'BB');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 3', 65, 97, 'CC', 'CC');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 4', 66, 161, 'DD', 'DD');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 1', 67, 129, 'AA', 'AA');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 5', 68, 129, 'AA', 'AA');
INSERT INTO PUBLIC.TEAM (NOMTEAM, ID, USERDIVISION_ID, TEAMBOSSNAME, TEAMBOSSEMAIL) VALUES ('TEAM 8', 69, 129, 'AA', 'AA');