INSERT INTO PUBLIC.USER_PRODUCT (USER_ID, PRODUCTS_ID) VALUES (1, 1);
INSERT INTO PUBLIC.USER_PRODUCT (USER_ID, PRODUCTS_ID) VALUES (1, 2);
INSERT INTO PUBLIC.USER_PRODUCT (USER_ID, PRODUCTS_ID) VALUES (2, 1);
INSERT INTO PUBLIC.USER_PRODUCT (USER_ID, PRODUCTS_ID) VALUES (3, 1);